
# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST https://localhost:7284/prova/funcionario/cadastrar
Content-Type: application/json

{
    "nome": "ovo",
    "cpf" : "12345676"
}

### Obtenção de todos os funcionários
GET https://localhost:7284/prova/funcionario/listar

# FOLHA ############################################

### Criação de uma nova folha
POST https://localhost:7284/prova/folha/cadastrar
Content-Type: application/json

{
    "valor": 50,
    "quantidade" : 100,
    "mes" : 10,
    "ano" : 2023,
    "funcionarioId" : 5
}

### Obtenção de todas as folhas
GET https://localhost:7284/prova/folha/listar

###
PUT https://localhost:7284/prova/funcionario/editar/2
Content-Type: application/json

{
    "Id": 2,
    "nome": "testinho",
    "cpf" : "12345678916"
}


### Obtenção de uma folha
GET https://localhost:7284/prova/folha/listar/12345676/10/2023